services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Perpustakaan
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/public/storage
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:DwtrPn73HPko69CcOmQ/bqPRVZzuLzvxg17/EPvfgc8=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

    networks:
      - laravel-network

volumes:
  storage-data:

networks:
  laravel-network:
    driver: bridge
